name: Swift Build & Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Swift 6.1
        uses: fwal/setup-swift@v1
        with:
          swift-version: "6.1"

      - name: Build project
        run: swift build --build-tests

      - name: Install SwiftLint
        run: |
          curl -L https://github.com/realm/SwiftLint/releases/download/0.54.0/swiftlint_linux.zip -o swiftlint.zip
          unzip swiftlint.zip -d swiftlint
          sudo mv swiftlint/swiftlint /usr/local/bin
          swiftlint version

      - name: Run SwiftLint
        run: swiftlint --strict
